### ISSUE TITLE
"nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text"

### ISSUE THREAD

**Issue by mawkler** [David-Kunz/jester#16]
Hi! After calling `:lua require('jester').debug()` I get the following warning which I'm guessing is because the plugin needs to be updated to Neovim's new treesitter api:

```
nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text
```

**Comment by David-Kunz** [comment]
Hey @melkster ,

Thanks for opening up that issue, I changed the code to use `vim.treesitter.query.get_node_text` instead.

https://github.com/David-Kunz/jester/commit/08ab0aa51ac35f85ca07a23a25bcc3927974efaa

Best regards,
David
