### ISSUE TITLE
Example Typescript Conifg

### ISSUE THREAD

**Issue by phortonssf** [David-Kunz/jester#21]
Trying to get this to work with typescript. Is it asking too much to post a sample typescript config? Thank you.

**Comment by vuki656** [comment]
What problems did you encounter? I use it with TS.

**Comment by David-Kunz** [comment]
Hi @phortonssf ,

What's the difference in combination with TypeScript? Any special handling needed?

**Comment by nabn** [comment]
I think the problem is monorepos. My jest config lives in <git_root>/ui, but this plugin seems to want to run jest from the <git_root>. 

Would be cool if there was a way to pass the path to jest config file.

**Comment by David-Kunz** [comment]
Hi @nabn,

I think you can do that already today by adjusting the jest path (and include the config via `-c <config>`), would that work?

**Comment by nabn** [comment]
@David-Kunz thanks for the tip. I was able to make it work by setting `path_to_jest_run` to `yarn workspace ui jest` and that correctly picked up the config. 

Bit odd that it's a command rather than a path, but I'm glad it works 🎉
