### ISSUE TITLE
The selected configuration references adapter `node2`, but dap.adapters.node2 is undefined

### ISSUE THREAD

**Issue by second-shadow** [David-Kunz/jester#23]
Hi!
Im trying to debug a jest test file with :lua require"jester".debug_file()
It throws me the following error:
The selected configuration references adapter `node2`, but dap.adapters.node2 is undefined

Im testing an API rest using javascript/NodeJS and I dont know anything (so far) about lua coding, sorry :)
Thanks in advance!
Regards.

**Comment by David-Kunz** [comment]
Hi @second-shadow ,

You need to install a debug adapter for [nvim-dap](https://github.com/mfussenegger/nvim-dap).

Here's a guide on how to do it for Node.js:
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Javascript

Here's my configuration for a working example: 
https://github.com/David-Kunz/vim/blob/88e1cd35dcc591fae90066d311dfd59320df974f/init.lua#L397

**Comment by second-shadow** [comment]
Hi!
I'll check it, thanks a lot!!
________________________________
De: Dr. David A. Kunz ***@***.***>
Enviado: miércoles, 22 de febrero de 2023 8:02
Para: David-Kunz/jester ***@***.***>
Cc: second-shadow ***@***.***>; Mention ***@***.***>
Asunto: Re: [David-Kunz/jester] The selected configuration references adapter `node2`, but dap.adapters.node2 is undefined (Issue #23)


Hi @second-shadow<https://github.com/second-shadow> ,

You need to install a debug adapter for nvim-dap<https://github.com/mfussenegger/nvim-dap>.

Here's a guide on how to do it for Node.js:
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Javascript

Here's my configuration for a working example:
https://github.com/David-Kunz/vim/blob/88e1cd35dcc591fae90066d311dfd59320df974f/init.lua#L397

**Comment by second-shadow** [comment]
Hi! 
I forgot to mention it, Im using vimspector for debugging as you show in your video and nvim on Windows. So, it is nvim-dap a substitude for this? It is redundant to have both installed?

**Comment by David-Kunz** [comment]
Hi @second-shadow ,

Yes, you can use `nvim-dap` (optionally with `nvim-dap-ui`) as a substitute for Vimspector.

**Comment by David-Kunz** [comment]
Closing this issue, hope everything works, @second-shadow !

**Comment by mawkler** [comment]
Hi! I'm getting the same error after switching from the deprecated [node-debug2](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#node-debug2) to [vscode-js-debug](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#vscode-js-debug) (using the [nvim-dap-vscode-js](https://github.com/mxsdev/nvim-dap-vscode-js) plugin). In [your previous comment](https://github.com/David-Kunz/jester/issues/23#issuecomment-1440311989) you link to vscode-js-debug even though in your own configuration that you linked you seem to be using node-debug2. Is it possible to use Jester with vscode-js-debug?

**Comment by David-Kunz** [comment]
Hi @mawkler ,

Yes, it's possible to user `vscode-js-debug`, however I had some issues with it last time I tried it. It would always open a different file when debugging, but that's how `vscode-js-debug` is designed (similar issues happen in VSCode).

Best regards,
David

**Comment by mawkler** [comment]
@David-Kunz I see! Do you have an example of a config that works? I get the error in the title of this issue when trying to start the debugger with `vscode-js-debug`.

**Comment by David-Kunz** [comment]
Did you configure it according to `mxsdev/nvim-dap-vscode-js`?

```lua
require("dap-vscode-js").setup({
  -- node_path = "node", -- Path of node executable. Defaults to $NODE_PATH, and then "node"
  -- debugger_path = "(runtimedir)/site/pack/packer/opt/vscode-js-debug", -- Path to vscode-js-debug installation.
  -- debugger_cmd = { "js-debug-adapter" }, -- Command to use to launch the debug server. Takes precedence over `node_path` and `debugger_path`.
  adapters = { 'pwa-node', 'pwa-chrome', 'pwa-msedge', 'node-terminal', 'pwa-extensionHost' }, -- which adapters to register in nvim-dap
  -- log_file_path = "(stdpath cache)/dap_vscode_js.log" -- Path for file logging
  -- log_file_level = false -- Logging level for output to file. Set to false to disable file logging.
  -- log_console_level = vim.log.levels.ERROR -- Logging level for output to console. Set to false to disable console output.
})

for _, language in ipairs({ "typescript", "javascript" }) do
  require("dap").configurations[language] = {
    ... -- see below
  }
end
```

**Comment by David-Kunz** [comment]
Check also the repository: https://github.com/mxsdev/nvim-dap-vscode-js

**Comment by mawkler** [comment]
@David-Kunz 

> Did you configure it according to the `mxsdev/nvim-dap-vscode-js?`

Yes, [this is my config](https://github.com/mawkler/nvim/blob/master/lua/configs/dap.lua#L128-L138) 🙂

**Comment by David-Kunz** [comment]
Ok, did you configure the appropriate `dap` config in Jester?

```lua
{
  ...,
  dap = { -- <----------------------
    type = 'node2',
    request = 'launch',
    cwd = vim.fn.getcwd(),
    runtimeArgs = {'--inspect-brk', '$path_to_jest', '--no-coverage', '-t', '$result', '--', '$file'},
    args = { '--no-cache' },
    sourceMaps = false,
    protocol = 'inspector',
    skipFiles = {'<node_internals>/**/*.js'},
    console = 'integratedTerminal',
    port = 9229,
    disableOptimisticBPs = true
  }
}
```

**Comment by mawkler** [comment]
@David-Kunz Isn't that set by default? If I add the following to my config I still get the same error message.

```lua
require('jester').setup({
  dap = {
    type = 'node2',
    request = 'launch',
    cwd = vim.fn.getcwd(),
    runtimeArgs = {'--inspect-brk', '$path_to_jest', '--no-coverage', '-t', '$result', '--', '$file'},
    args = { '--no-cache' },
    sourceMaps = false,
    protocol = 'inspector',
    skipFiles = {'<node_internals>/**/*.js'},
    console = 'integratedTerminal',
    port = 9229,
    disableOptimisticBPs = true
  }
})
```

But what is node2 anyway? It looks from the error like it wants me to call `require('dap').adapters.node2 = {}` somewhere, but what do I set `node2` it to? 🤔

**Comment by David-Kunz** [comment]
@mawkler , Yes, this is the default, you need to adjust it for `pwa-node`, i.e.

```lua
require'jester'.setup({ dap = { type = 'pwa-node'}})
```

**Comment by mawkler** [comment]
@David-Kunz Aha I see, thank you! Now however I'm seeing a totally different error:

```
[dap-js] JS Debugger stderr: /home/melker/.local/share/nvim/mason/packages/js-debug-adapter/dist/src/vsDebugServer.js:58
See: https://github.com/isaacs/node-glob/issues/167

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

```

The linked issue is from 2015 and I have no idea what it has to do with js-debug-adapter 🤔

**Comment by David-Kunz** [comment]
Hi @mawkler ,

I think you just need to upgrade your `node` version (where the `??=` operator is supported).

Best regards,
David

**Comment by mawkler** [comment]
@David-Kunz Aha that makes sense, thank you I'll give that a try!
