### ISSUE TITLE
Support running debugger through yarn

### ISSUE THREAD

**Issue by rockerBOO** [David-Kunz/jester#3]
Yarn (and maybe other package managers) support different ways of storing dependancies. This makes the local node modules not compliant in those cases. https://yarnpkg.com/features/pnp/#initializing-pnp

For example running `:lua require"jester".debug()`
```
Debugger listening on ws://127.0.0.1:9229/08a2389d-5a16-4aed-9437-48d1d61740d3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/rockerboo/code/ecogarden/create/node_modules/.bin/jest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[Process exited 1]
```
The suggestion is to run `yarn run --inspect --inspect-brk jest` instead. This will look up the binary and apply the inspects for the debugger.

I think with this example it starts running a node process so would need to pass through the suggested paths

```
node -r ./.pnp.cjs ./server.js
NODE_OPTIONS="--require $(pwd)/.pnp.cjs" node ./server.js
```
I am also working with yarn workspaces so these 2 modes are not generally good enough to automate depending on where I am in the workspaces.

**Comment by David-Kunz** [comment]
Hi @rockerBOO,

Thanks for opening this issue.

In your case, you can configure the `dap.runtimeArgs` option:

```lua
require"jester".debug_file({
  dap = { runtimeArgs = {'yarn', 'run', '--inspect', '--inspect-brk', 'jest', '--no-coverage', '-t', '$result', '--', '$file'}}
})
```

Would that work for you?

Background: It's hard to find a one-size-fits-all solution as the jest installation can be different.

Thanks and best regards,
David

**Comment by David-Kunz** [comment]
Note: I now also slightly changed `path_to_jest`, it's now used both for running debugging Jest tests.

**Comment by rockerBOO** [comment]
I haven't had time to move over from my fork but I was able to get it working at least. 

Overall can set node2 to use yarn 

```
local dap = require('dap')
    dap.adapters.node2 = {
      type = "executable",
      command = "yarn",
      args = { "node", os.getenv("HOME") .. "/build/vscode-node-debug2/out/src/nodeDebug.js" },
    }
```
and then something like this

```
require"jester".debug_file({
  dap = { runtimeArgs = { 'run', '--inspect', '--inspect-brk', 'jest', '--no-coverage', '-t', '$result', '--', '$file'}},
  path_to_jest = 'jest'
})
```
So that seems to work for now. I only use yarn for my projects currently so this works out. Thanks @David-Kunz !

**Comment by rockerBOO** [comment]
Actually I have another thing in my fork I can hopefully open up but maybe setting the runtimeExecutable value in dap is adequate?

In my fork I have this in the `debug_jest` function I have
```
    local runtimeExecutable = 'node'
    if o.yarn then
      runtimeExecutable = 'yarn'
    end
    dap.run({
           ...
          runtimeExecutable = runtimeExecutable,
          ...
    })
```

This is more for anyone who needs context of where I changed things to get yarn executing currently.
