### ISSUE TITLE
Can't find nearest test when cursor is on a comment

### ISSUE THREAD

**Issue by kahnclusions** [David-Kunz/jester#5]
Nice plugin!

I'm experimenting with this in a TypeScript project and noticed what may be a little bug. If the cursor is directly over a comment, then it seems like it is unable to traverse the parent nodes to find the nearest "test" block. But moving anywhere else inside the test function locates it perfectly fine.

**Comment by David-Kunz** [comment]
Hi @kahnclusions ,

Thanks for this report, yes, that's also something I noticed.
The reason is that comments are at the top level of the AST.
I will fix it as soon as I have some time!

Best regards,
David

**Comment by David-Kunz** [comment]
Hi @kahnclusions ,

I fixed the bug: https://github.com/David-Kunz/jester/commit/68a87c5e7c9afa2d9a1d32cb6a3fc109122cbc2d, it's in the main branch so you can just upgrade your package.

It would be great if you could tell me if that fixes your problem.

Thanks again and best regards,
David

**Comment by kahnclusions** [comment]
Yes! Can confirm it works now. Thanks for the quick fix @David-Kunz  🔧
